[pytest]
testpaths=tests 
python_files=test_*.py 
python_functions=test_*
addopts= -v --html=reports/report.html --self-contained-html
markers=
     smoke:Critical tests that verify the main functionality 
     regression:Complete regression test suite
     login:Tests related to login functionality